<a href="https://colab.research.google.com/github/CarolineAndradeR/Data-Science/blob/main/Processamento%2C_manipula%C3%A7%C3%A3o_e_visualiza%C3%A7%C3%A3o_de_dados_com_Phytton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY -** É uma bibloteca para Python, significa Python Númerico. É a principal biblioteca para trablhar com álgebra linear, estrutura de dados e algoritmos de Ciência de Dados. É umas das prinpais bibliotecas para e trabalhar com ciência de dados.

In [1]:
# Essa biblioteca não vem instalada no pacote padrão do Python, precisamos instalar a biblioteca
import numpy as np

In [2]:
# Uma estrutura de dados parecida com uma lista, porém os objetos dessa array devem ser do mesmo tipo.
a =  np.array({1,2,3}) # Criação de uma array, uma lista unidimensional.

In [3]:
# Uma estrutura de lista da lista, que se torna uma matriz
b =  np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
# Retorna a dimensão da estrutura dos dados
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


**Outras formas de criar array**

In [ ]:
# Cria uma array de zeros onde a dimensão quadrada de 2 por 2
a = np.zeros((2,2))
print(a)

# Cria uma array de um (1), uma linha e duas colunas onde os valores são de um.
b = np.ones((1,2))
print(b)

# Cria uma array de constante, são valores diferentes de 0 e de 1 onde será uma matriz de 7 de 2 por 2.
c = np.full((2,2),7)
print(c)

# Cria uma matriz indentidade, é uma matriz que na diagonal principal contem valores unitários.
d = np.eye(2)
print(d)

# Cria uma matriz quadrada de números aleatórios.
e = np.random.random((2,2))
print(e)

**Indexação de Array**

Acessar os elementos de uma array para manipular os dados. Em um projeto de ciência de dados sempre teremos a necessidade de relizar a limpeza e manipulação dos dados.

In [6]:
import numpy as np

# Criar um array de bi-dimensional, que contém 3 linhas e 4 colunas
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Acessar o elemento que queremos acessar
# Coluna 0 linha 1, segundo elemente a primeira linha.
print(a [0,1])

# Trocando os valores dessa posição, o valor de 2 passa a ser 77.
a[0,1] = 77

print(a[0,1])

2
77


In [8]:
# Fatiamento de array - acessar dados de um determinado intervalo.
# Os primeiros valores são de linhas e o segundo são os valores das colunas.
# Sem dados antes do : significa que vamos trabalhar com o ínicio do array (indice zero).

b = a[:2, 1:3]

print(a);
print(b)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[77  3]
 [ 6  7]]


In [11]:
# Retorna todos os dados da linha 1 de todas as colunas.
# quando não é passado nada entre o : é retornado todos os dados.
linha_1 = a[1, :]

coluna_1 = a[:, 1]

print(linha_1)
print(coluna_1)

[5 6 7 8]
[77  6 10]


**Realizando cálculos**

In [12]:
import numpy as np

# Criação dos array
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# Soma dos dados ponto a ponto (vai soma o valor de 1 + 5, 2 + 6.)
print(x + y)
print(np.subtract(x, y))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
