<a href="https://colab.research.google.com/github/CarolineAndradeR/Data-Science/blob/main/Processamento%2C_manipula%C3%A7%C3%A3o_e_visualiza%C3%A7%C3%A3o_de_dados_com_Phytton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY -** É uma bibloteca para Python, significa Python Númerico. É a principal biblioteca para trablhar com álgebra linear, estrutura de dados e algoritmos de Ciência de Dados. É umas das prinpais bibliotecas para e trabalhar com ciência de dados.

In [ ]:
# Essa biblioteca não vem instalada no pacote padrão do Python, precisamos instalar a biblioteca
import numpy as np

In [ ]:
# Uma estrutura de dados parecida com uma lista, porém os objetos dessa array devem ser do mesmo tipo.
a =  np.array({1,2,3}) # Criação de uma array, uma lista unidimensional.

In [ ]:
# Uma estrutura de lista da lista, que se torna uma matriz
b =  np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Retorna a dimensão da estrutura dos dados
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


**Outras formas de criar array**

In [ ]:
# Cria uma array de zeros onde a dimensão quadrada de 2 por 2
a = np.zeros((2,2))
print(a)

# Cria uma array de um (1), uma linha e duas colunas onde os valores são de um.
b = np.ones((1,2))
print(b)

# Cria uma array de constante, são valores diferentes de 0 e de 1 onde será uma matriz de 7 de 2 por 2.
c = np.full((2,2),7)
print(c)

# Cria uma matriz indentidade, é uma matriz que na diagonal principal contem valores unitários.
d = np.eye(2)
print(d)

# Cria uma matriz quadrada de números aleatórios.
e = np.random.random((2,2))
print(e)

**Indexação de Array**

Acessar os elementos de uma array para manipular os dados. Em um projeto de ciência de dados sempre teremos a necessidade de relizar a limpeza e manipulação dos dados.

In [ ]:
import numpy as np

# Criar um array de bi-dimensional, que contém 3 linhas e 4 colunas
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Acessar o elemento que queremos acessar
# Coluna 0 linha 1, segundo elemente a primeira linha.
print(a [0,1])

# Trocando os valores dessa posição, o valor de 2 passa a ser 77.
a[0,1] = 77

print(a[0,1])

2
77


In [ ]:
# Fatiamento de array - acessar dados de um determinado intervalo.
# Os primeiros valores são de linhas e o segundo são os valores das colunas.
# Sem dados antes do : significa que vamos trabalhar com o ínicio do array (indice zero).

b = a[:2, 1:3]

print(a);
print(b)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[77  3]
 [ 6  7]]


In [ ]:
# Retorna todos os dados da linha 1 de todas as colunas.
# quando não é passado nada entre o : é retornado todos os dados.
linha_1 = a[1, :]

coluna_1 = a[:, 1]

print(linha_1)
print(coluna_1)

[5 6 7 8]
[77  6 10]


**Realizando cálculos**

In [ ]:
import numpy as np

# Criação dos array
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# Soma dos dados ponto a ponto (vai soma o valor de 1 + 5, 2 + 6.)
# Podemos chamar de matriz por ser um modelo unidimensional
# Soma entre as matrizes
print(x + y)
print(np.add(x,y))

# Subtração entre as matrizes
print(x - y)
print(np.subtract(x, y))

# Multiplicação entre as matrizes
print(x * y)
print(np.multiply(x, y))

# Divisão entre as matrizes
print(x / y)
print(np.divide(x, y))

# Calcula a raiz quadrada de toda a matriz
print(np.sqrt(x))

In [9]:
# .dot - linha x coluna
# Criação dos array
# Multica-se os elementos da primeira linha da primeira matriz x os elementos da segunda matriz
# Exemplo: 1*5+2*7
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

# Com a matriz unidimensional
# = 9*11 + 10*12
v = np.array([9, 10])
w = np.array([11, 12])

# Multiplicação de Matriz
# x*y
print(x.dot(y))
# Pode usar um metodo e passar os paramentros
print(np.dot(v, w))
print(v @ w)

[[19 22]
 [43 50]]
219
219


In [11]:
# Array N dimensional
#
x = np.array([[1,2], [3,4]])

# Soma todos os elementos do array x
print(np.sum(x))
# Eixo 0 retorna soma das colunas
print(np.sum(x, axis=0))
# Eixo 1 retorna a soma das linhas
print(np.sum(x, axis=1))

10
[4 6]
[3 7]
